### ISSUE TITLE
Remote Peer No Audio

### ISSUE THREAD

**Issue by BlazenBundy** [aws/connect-rtc-js#16]
Using the connect-rtc api in conjunction with the streams api with a successfully connected inbound call the remote connected peer audio is not outputting to the speakers, in fact I don't even think the real time audio is making it to the browser?

Example initialisation

```
var ccpUrl = "https://{awsusername}.awsapps.com/connect/ccp#/";

  connect.core.initCCP(containerFrame, {
      ccpUrl: ccpUrl,
      loginPopup: true,
      softphone: {
        allowFramedSoftphone: false
      }
  });
  connect.core.initSoftphoneManager({allowFramedSoftphone: true});
```

If you comment out softphone manager and fall back on just CCP then when the call is connected remote peer connected audio outputs to the correct output device?

```
var ccpUrl = "https://{awsusername}.awsapps.com/connect/ccp#/";

  connect.core.initCCP(containerFrame, {
      ccpUrl: ccpUrl,
      loginPopup: true,
      softphone: {
        allowFramedSoftphone: true
      }
  });
  //connect.core.initSoftphoneManager({allowFramedSoftphone: true});
```

Is anyone else experiencing no remote peer audio or have I incorrectly configured or misinterpreted how to use the API's together?

Cheers,

Bundy

**Comment by yuliangz** [comment]
Just to clarify, with the second code snippet, you can hear the remote audio, right?
Sorry that we didn't provide the complete information to help you integrate. Will update README file soon. But to unblock you, could you try adding an audio HTML element with ID "remote-audio" to your own page?

**Comment by BlazenBundy** [comment]
@yuliangz I get absolutely no remote audio, only one way speech from the local peer out through the microphone. Zero positive energy is presented to the outputdevice (Speakers). 

So I'm guessing based on what you have said I need to place the audio element with id=remote-audio into the parent document (instead of?/in addition to?) letting the same element that is appended to the containerFrame's iframe during initCCP? Because that audio element with that id already exists in the DOM however it is positioned as I said just then down in the containerFrame's iframe document.

Just trying to clarify if that is what you are asking?

**Comment by BlazenBundy** [comment]
And sorry yes with the second code snippet so initialising with initCCP alone with no softphoneManager I do get remote audio (positive energy) through the outputdevice (speakers). I should have answered that first.

**Comment by yuliangz** [comment]
Yes, that is right. With your first code snippet, you are essentially asking stream-js to handle softphone call on parent document, then it will look for remote-audio element from parent document. The one in iframe wouldn't be invoked at all.

**Comment by BlazenBundy** [comment]
@yuliangz 

Ok firstly I want to thank you for your recommendation of placing the audio element into the parent document it was the ultimate resolution to aligning the remote peer audio to the connect session. 

NOTE: You cannot simply add the following:

`<audio id="remote-audio"></audio>`

As I discovered the remote stream does get assigned to the source of the element however the element is starting in a paused state and therefore audio is muted. I got around this by adding the autoplay attribute to the element like so: 

`<audio id="remote-audio" autoplay></audio>`

I'm sure you could do this on the fly before invoking the initCCP with something like:

```
//ensure audio element is present in parent document with autoplay for remote peer audio
var audioElement = document.createElement('audio');
    audioElement.id = 'remote-audio';
    audioElement.setAttributeNode(document.createAttribute('autoplay'));
    document.body.insertBefore(audioElement, document.body.firstChild);

//configure your connect instance
var ccpUrl = "https://{awsusername}.awsapps.com/connect/ccp#/";

//initialise the softphone into your container
    connect.core.initCCP(containerFrame, {
       ccpUrl: ccpUrl,
       loginPopup: true,
       softphone: {
          allowFramedSoftphone: false
       }
    });

//initialise the softphone manager to handle the session using connect-rtc API WOOT WOOT =P
     connect.core.initSoftphoneManager({allowFramedSoftphone: true});
```

Once again thanks heaps @yuliangz we can flag this configuration bug as solved!

Cheers,

Bundy =)
![bitmoji](https://render.bitstrips.com/v2/cpanel/27b14f57-f25e-4eb2-a4e5-b75e089c772a-56da9a33-17d1-4f32-ba81-e7e406816e23-v1.png?transparent=1&palette=1&width=246)

**Comment by yuliangz** [comment]
Thanks for reporting the issue and verifying the fix. I will make sure README is updated before closing this issue.

**Comment by yuliangz** [comment]
README updated.
