### ISSUE TITLE
RtcSession.mediaStream is not getting used

### ISSUE THREAD

**Issue by alonch** [aws/connect-rtc-js#25]
## Issue  
If I use `connect.core.initSoftphoneManager()` on streams api, the session tries to get the microphone from the browser, even tho a stream has been provided 

## Solutions
on line 
https://github.com/aws/connect-rtc-js/blob/b363655d6fc5ddb13c17ca8c850f17156ffdf471/src/js/rtc_session.js#L71

`_userAudioStream` has been refactored to`_localStream`  

This test will need fixing after the change
https://github.com/aws/connect-rtc-js/blob/4959a1abe6d35669e8099ce3ac26197f950bddfb/test/unit/rtc_session.js#L84

**Comment by yiming-amzn** [comment]
This is addressed in v1.1.16
