### ISSUE TITLE
Polling for MediaRtpStats is causing error to bubble up

### ISSUE THREAD

**Issue by ddruker** [aws/connect-rtc-js#57]
Currently when waiting to accept or reject an incoming call we are noticing that the sdk is calling `getStats`, which is causing the logged error to bubble up into our application.

The error below is appearing on the latest Chrome. Im not seeing the error on Firefox.

> Uncaught Error: Failed to extract MediaRtpStats from RTCStatsReport for stream type audio_input

This may be a configuration issue on our part but we are only seeing this in the newest release. Having the ccp open in another tab removes the error but this is not how our users interact with the application.

**Comment by Randomnation** [comment]
I know this is an old post, but I was wondering if anything had progressed with this one? I am having the exact same issue currently. Using Firefox is not really a viable option for us as we can't rely on a nightly build that has no support.

**Comment by star-square** [comment]
I and my team are having the same issue, bumping this.

**Comment by CiscoKidxx** [comment]
Bump

**Comment by Solomon-m** [comment]
Hello, 
We are having this same issue in our Custom CCP panel. We are loading our CCP panel in the Electron application which is using the Chromium browser engine. After user login, we could see the following error for the First incoming call/outbound call .
```
 Uncaught Error: Failed to extract MediaRtpStats from RTCStatsReport for stream type audio_input
```
Any fix or suggestion on this issue is much appreciated.

**Comment by Solomon-m** [comment]
Hi @gargvk10 
Good Day. Anyone looking into this issue ? Any comments or suggestion on this issue would be helpful for us.

Thank you.

**Comment by yiming-amzn** [comment]
Hi, this issue is resolved in https://github.com/aws/connect-rtc-js/releases/tag/v1.1.19
Thanks!
