### ISSUE TITLE
Versions > v1.1.3 causes signalling_handshake_failure with the latest connect streams 1.4.4

### ISSUE THREAD

**Issue by yeoji** [aws/connect-rtc-js#59]
I'm trying to integrate connect streams 1.4.4 with the latest version of connect-rtc and have found compatibility issues. I raised an issue with connect-streams [here](https://github.com/amazon-connect/amazon-connect-streams/issues/229) but I think the issue lies with the connect-rtc project.

Using connect streams 1.4.4 with connect rtc 1.1.3 seems to work.

The error I get is `signalling_handshake_failure` and the softphone shows:

<img width="327" alt="Screen Shot 2020-03-03 at 9 37 19 am" src="https://user-images.githubusercontent.com/8002179/75944740-9d259480-5eec-11ea-906c-d97d73d780fe.png">

**Comment by gargvk10** [comment]
connect-rtc-js version > v1.1.3 and connect stream 1.4.4 version must use CCP V2 endpoint.
<script>
        var softphoneDiv = document.getElementById('softphone');

        // Modify this with your Connect details
        var yourCCPPage = 'https://blabla.awsapps.com/connect/ccp-v2/'

        var softphoneParams = {
            ccpUrl: yourCCPPage,
            loginPopup: true,
            loginPopupAutoClose: true,
            softphone: {
                allowFramedSoftphone: false
            }
        };
        connect.core.initCCP(softphoneDiv, softphoneParams);
        connect.core.initSoftphoneManager({ allowFramedSoftphone: true });
</script>
