### ISSUE TITLE
Reasoning behind browser limitations?

### ISSUE THREAD

**Issue by davidthornton** [aws/connect-rtc-js#85]
Hi all, I realise this isn't an issue -- but is there any documentation as to why other browsers are not supported? Is it a webRTC implementation thing, a tab/threading/sleep thing or is it that the official Amazon Connect full feature set is only compatible with Firefox, Chrome and Opera capabilities?

Thanks,
David

**Comment by Akash1684** [comment]
Amazon connect now supports Edge Chromium. Please refer to the official announcement here https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-connect-supports-edge-chromium/
