### ISSUE TITLE
Connect-rtc.js not working on some Connect Instances

### ISSUE THREAD

**Issue by huseyinzorlu** [aws/connect-rtc-js#94]
We are using connect-rtc.js without Amazon Connect StreamJS and it works by receiving Media Info JSON. However, in some US instances, connect-rtc.js Media Info JSON format is different. Issue only happens in the US regions. Rest of the world is fine. 

//Good Call
"callConfigJson": "{\"signalingEndpoint\":\"[wss://rtc.connect-telecom.us-east-1.amazonaws.com/LilyRTC\](wss://rtc.connect-telecom.us-east-1.amazonaws.com/LilyRTC/)",\"iceServers\":[{\"urls\":[\"turn:[turnnlb-d76454ac48d20c1e.elb.us-east-1.amazonaws.com](http://turnnlb-d76454ac48d20c1e.elb.us-east-1.amazonaws.com/).:3478?transport=udp\"],,\"protocol\":\"LilyRTC/1.0/WSS\",\"useWebSocketProvider\":true}"

//Bad Call
"callConfigJson": "{\"signalingEndpoint\":\"/LilyRTC\",\"iceServers\":[{\"urls\":[\"turn:[turnnlb-7a9b8e750cec315a.elb.us-east-1.amazonaws.com](http://turnnlb-7a9b8e750cec315a.elb.us-east-1.amazonaws.com/).:3478?transport=udp\"],\\"protocol\":\"LilyRTC/1.0/WSS\",\"useWebSocketProvider\":true}"

//Removed params: username, credentials, sessionToken

If the AWS ID used is relatively new, i.e. ID registered in the last 12 months, any Connect instance created using that account ID has a different media info JSON.

If we create a NEW Connect instance TODAY, the behavior is not identical worldwide;
//Connect-RTC Good / Bad Media Info

Old AWS ID (Created earlier than 12 months)   US Regions:Good   RoW:Good
New AWS ID (Created within last 12 months)    US Regions:Bad    RoW:Good

Anyone experienced similar behavior and any ideas for resolution?

**Comment by yiming-amzn** [comment]
In CCPv1, fields like `signalingEndpoint` is used to setup the softphone connection. When we only have CCPv1, all the regions and instances will have a valid value for `signalingEndpoint`
In CCPv2, we do not use `signalingEndpoint` to setup the softphone connection. For new regions and instances, that `signalingEndpoint` could be invalid because CCPv2 does not need it. 
For CCPv2, you can follow how streamJs initialized the rtcSession here: https://github.com/amazon-connect/amazon-connect-streams/blob/master/src/softphone.js#L209

**Comment by yiming-amzn** [comment]
Closing the issue as the we are not planning to support CCPv1 specific configurations, like `signalingEndpoint`, for new instances.

**Comment by huseyinzorlu** [comment]
I understand, but I'd like to ask: if we can't obtain the signalingEndpoint, how can we initiate a call using this code?

```
var session = new connect.RTCSession(rtcConfig.signalingEndpoint,
            rtcConfig.iceServers,
            mediaInfo.callContextToken,
            console);

```
Furthermore, it seems not to work ( In demo page ) when trying to answer a call. Why might that be?"
